config/routes.rb
Minisite::Application.routes.draw do

  resources :entries

 root :to => "tags#show"
    
 match 'tags/:name' => 'tags#show'
    
 match 'tags/' => 'tags#show'
    

end

app/models/entry.rb
class Entry < ActiveRecord::Base

 attr_accessible :name,:image,:content,:id,:title,:tags_attributes
 
 has_many :tags, :dependent => :delete_all
 
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
 # Method mount_uploader needed to attach uploader
 mount_uploader :image, ImageUploader
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    validates :name, :format => { :with => /\A[a-zA-Z]+\z/, :message => "Only letters allowed" }

  belongs_to :entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, :notice => 'Entry was successfully created.' }
        format.json { render :json => @entry, :status => :created, :location => @entry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, :notice => 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @entries = Entry.all

    respond_to do |format| # Calles the responder on the AppkicationController .. do ... end is the parameter 
		#|format| stands for a single argument taken 
		
      format.html # index.html.erb
      format.json { render :json => @entries }
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /tags/1
  # GET /tags/1.json
  def show
      
      # @tags = Tag.where(:name => params[:name])
      
      if ( params[:name] != nil) 
          @entries =   Entry.includes([:tags]).where(['tags.name = ?', params[:name]]).all
      else 
         @entries = Entry.all
      end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @entry }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entries/_form.html.erb
<% @entry.tags.build %>
<%= form_for(@entry, :html => {:multipart => true}) do |post_form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>

  <div class="field">
    <%= post_form.label :image %><br />
    <%= post_form.file_field :image %>
  </div>

  <div class="actions">
    <%= post_form.submit %>
  </div>

<h2>Tags</h2>
<%= render :partial => 'tags/form',
:locals => {:form => post_form} %>
<div class="actions">
<%= post_form.submit %>
</div>

<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.name %></td>
    <td><%= entry.title %></td>
    <td><%= entry.content[0..50] %></td>
    <td><%if entry.image_url != nil %>
            <%= "yes" %>
        <% else %>
           <%= "no" %>
        <% end %>
    </td>


    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/home/index.html.erb
=begin
#Deprecated
<% @uniqueTags = Tag.find(:all, :select => 'DISTINCT name') %>
<div id="tags">
<% @uniqueTags.each do |entry| %>
    <a href=""><%= entry.name %></a>,
<% end %>
	
</div>
<div id="container" > 
<div id="box">	

<%= link_to "Adminview", entries_path %>

<table>

<% if @entries.size % 2 != 0
        playholderEntry = Entry.new
        playholderEntry.name = "..."
        playholderEntry.title = "..."
        @entries.push playholderEntry
    end

%>
<% @entries.each_with_index do |entry,index| %>
    <% if index % 2 == 0 %>
    <tr>
    <%end %>
    
        <td >
            <div class="imagebox">
            <% if entry.image_url(:thumb) != nil %>
              <%= image_tag entry.image_url(:thumb) if entry.image? %>
            <%  else %>
              <%= entry.content %>
            <% end %>
            <span class="textbox">
            <%= entry.name %>  
            <%= entry.title %>
            </span>
            </div>

        </td>
        <% if index % 2 != 0 %>
        </tr>
        <%end %>
<% end %>
</table>


</div>
</div>
</div>
=end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<title>popinskis portfolio</title>

<%= stylesheet_link_tag    "application", :media => "all" %>
<%= stylesheet_link_tag    "jquery.fancybox-1.3.4.css", :media => "all" %>
<%= javascript_include_tag "jquery-ui-1.8.17.custom.min.js" %>
<%= javascript_include_tag "jquery.fancybox-1.3.4.js" %>
<%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>

<body>

<img src="/img/background.jpg" class="bg">


<div id="page-wrap">

<a href="/" ><img src="/img/popinski.png" style="border:none;" /> </a>

<%= yield %>



</body>

</html>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>

app/views/tags/show.html.erb
<script type="text/javascript">
$(document).ready(function() {

	/* This is basic - uses default settings */
	
	$("a.single_image").fancybox();
	
	/* Using custom settings */
	
	$("a.inline").fancybox({
		'hideOnContentClick': true
	});

	/* Apply fancybox to multiple items */
	
	$("a.group").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600, 
		'speedOut'		:	200, 
		'overlayShow'	:	false
	});
	
});
</script>

<% @uniqueTags = Tag.find(:all, :select => 'DISTINCT name') %>
<div id="tags">
<% @uniqueTags.each do |entry| %>
<a href="/tags/<%= entry.name %>"><%= entry.name %></a>,
<% end %>
<a href="/tags/">all</a>
</div>
<div id="container" > 
<div id="box">	

<%= link_to "Adminview", entries_path %>

<table>

<% if @entries.size % 2 != 0
	placeholderEntry = Entry.new
	placeholderEntry.name = "..."
	placeholderEntry.title = "..."
	@entries.push placeholderEntry
end

%>
<% @entries.each_with_index do |entry,index| %>
<% if index % 2 == 0 %>
	<tr>
<%end %>

<td >
<div class="imagebox">
	<% if entry.image_url(:thumb) != nil %>
		<!-- <a class="single_image" href="<%= entry.image_url %>"> -->
		<a class="inline" href="#data<%=index %>">
		<%= image_tag entry.image_url(:thumb) if entry.image? %>
	</a>
<%  else %>
		<a class="inline" href="#data<%=index %>">
		<%= entry.content %>
		</a>
<% end %>
<span class="textbox">
<%= entry.name %>  
<%= entry.title %>
</span>
</div>



</td>
<% if index % 2 != 0 %>
	</tr>
<%end %>

<div style="display:none"><div id="data<%=index %>">
		<% if entry.image_url(:thumb) != nil %>
			<a class="single_image" href="<%= entry.image_url %>">
				<%= image_tag entry.image_url() if entry.image? %>
			</a>
		<%  else %>
			<%= entry.content %>
		<% end %>
	
		<span class="textbox">
			<%= entry.name %>  
			<%= entry.title %>
		</span>
	</div>
</div>


<% end %>
</table>


</div>
</div>
</div>